version: '3'
services:
  tests:
    # use docker from src
    build: ./docker
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: ['/app/docker-entrypoint.sh']
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: database
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mariadb-admin" ,"ping", "-h", "127.0.0.1", "-uroot", "-p$$MARIADB_ROOT_PASSWORD" ]
      timeout: 2s
      retries: 10